api_keys:
  recall_api_url: "https://api.sandbox.competitions.recall.network/api"
  recall: "f6e81b4fc64763d8_b200b4fb26bbecdd"
  gaia: "gaia-NWM2YzIwODItM2M1Zi00NWQzLTg0OTItNDljNzZiOWExNjUy-F1jOmTF08AJoQsT-"
trade_limits:
  per_asset_daily: 50
  overall_daily: 100
scheduling:
  trades_per_day: 3
  trade_interval_minutes: 15 